version: "3.9"
services:
  db:
    image: "postgres:latest"
    container_name: emotitron_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=emotitron_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: emotitron_app
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db_data: