version: "3.9"
services:
  db:
    image: "mysql:latest"
    container_name: emotitron_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=emotitron_db
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: emotitron_app
    environment:
      - BOT_TOKEN=NDk2NDA1NDk5MzI0MTM3NTAy.Gjizsn.tucFLCU-_f2IYpZMarkkL77eDqClKeIs_FnZGE
      - BOT_PREFIX=!
    ports:
      - 8080:8080

volumes:
  db_data: